name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE : "true"
          SHOW_PROFILE_VIEWS : "true"
          SHOW_LANGUAGE_PER_REPO : "true"
          SHOW_LOC_CHART : "true"
          SHOW_SHORT_INFO : "true"
          SHOW_PROJECTS : "true"
          SHOW_TOTAL_CODE_TIME : "true"
          SHOW_TITLE : true

# name: Waka Readme

# on:
#   schedule:
#     # Runs at 12am IST
#     - cron: '30 18 * * *'
#   workflow_dispatch:
# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           # 时间线
#           SHOW_LOC_CHART: False

