

name: WakaTime Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 19 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}


# name: Waka Readme

# on:
#   workflow_dispatch:
#   schedule:
#     # Runs at 12am UTC
#     - cron: '0 0 * * *'

# jobs:
#   update-readme:
#     name: Update this repo's README
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_SHORT_INFO: "True"
#           SHOW_LINES_OF_CODE: "True"
#           SHOW_PROFILE_VIEWS: "True"
#           SHOW_DAYS_OF_WEEK: "True"
#           SHOW_OS: "True"
#           SHOW_PROJECTS: "False"
#           SHOW_COMMIT: "True"
#           SHOW_LANGUAGE: "True"
#           SHOW_EDITORS: "True"
#           SHOW_TIMEZONE: "True"
#           SHOW_LANGUAGE_PER_REPO: "True"
#           SHOW_LOC_CHART: "False"

# name: Waka Readme

# on:
#   schedule:
#     # Runs at 12am IST
#     - cron: '30 18 * * *'
#   workflow_dispatch:
# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           # 时间线
#           SHOW_LOC_CHART: False

